services:
    danieltj.verifiedprofiles.listener:
        class: danieltj\verifiedprofiles\event\listener
        arguments:
            - '@request'
            - '@template'
            - '@danieltj.verifiedprofiles.includes.functions'
        tags:
            - { name: event.listener }

    danieltj.verifiedprofiles.includes.functions:
        class: danieltj\verifiedprofiles\includes\functions
        arguments:
            - '@dbal.conn'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '%core.php_ext%'
