services:
    danieltj.verifiedprofiles.listener:
        class: danieltj\verifiedprofiles\event\listener
        arguments:
            - '@auth'
            - '@request'
            - '@template'
            - '@language'
            - '@danieltj.verifiedprofiles.includes.functions'
        tags:
            - { name: event.listener }

    danieltj.verifiedprofiles.includes.functions:
        class: danieltj\verifiedprofiles\includes\functions
        arguments:
            - '@auth'
            - '@dbal.conn'
